### ISSUE TITLE
Show a legend for plotted values

### ISSUE THREAD

**Issue by Seneo1** [matplotlib/mplfinance#408] opened 2021-06-15 09:34 UTC
```
import yfinance as yf, datetime as dt
ticker = "AAPL"
df = pd.DataFrame()
start = dt.datetime.today() - dt.timedelta(1825)
end = dt.datetime.today()
df[ticker] = yf.download(ticker, start, end)["Adj Close"]
df.fillna(method='bfill', axis=0, inplace=True)
df['200-day Exponential MA'] = df.ewm(span=200, adjust=False).mean()
df['50-day Exponential MA'] = df[ticker].ewm(span=50, adjust=False).mean()
df.plot()
```
This displays a plot with a legend of the ticker and a description of the moving averages. Does mplfinance have the same function?
![chart](https://user-images.githubusercontent.com/25407654/122029654-5734cd00-cdcd-11eb-9499-e4359dd7db50.jpg)

```
import mplfinance as mpf
df = yf.download(ticker, start, end)
mpf.plot(df, volume=True, tight_layout=True, style="binance", type="candle", mav=(50,200))
```
Because although this plots the averages, it is up to the viewer to guess which MA is which, and someone unfamiliar with the code would not be able to tell if it is an exponential or simple moving average. 
![chart2](https://user-images.githubusercontent.com/25407654/122029830-83e8e480-cdcd-11eb-92e3-9462b1400b43.jpg)

**Comment by DanielGoldfarb** [comment] 2021-07-14 19:12
duplicate of #276

**Closed by DanielGoldfarb** 2021-07-14 19:12 UTC
Labels: question
