### ISSUE TITLE
Use mplfinance with Tkinter

### ISSUE THREAD

**Issue by WHug0** [matplotlib/mplfinance#55] opened 2020-03-17 14:56 UTC
Hi, how can I embed my mplfinance graph in Tkinter ?

**Comment by DanielGoldfarb** [comment] 2020-03-17 15:20
See issue #46 ... That will do it.  (Read through the comments there, and see also some [example code](https://github.com/matplotlib/mplfinance/issues/46#issuecomment-596209866) given there as well).

If you would like to contribute the enhancement, please do.  Otherwise I expect to get around to it in about two weeks.

Duplicate of #46

**Closed by DanielGoldfarb** 2020-03-17 15:20 UTC
Labels: question

**Comment by WHug0** [comment] 2020-03-17 15:46
Ok, I will do this, thanks

**Comment by DanielGoldfarb** [comment] 2020-03-17 16:22
@WHug0 Thanks.   Perhaps return not only the Figure, but a `tuple`, where the first element is the `Figure`, and the second element is a `list` of the `Axes` that were created by `mpf.plot()`

**Comment by hmhjapan** [comment] 2021-01-02 09:06
@WHug0 :
Could you publish the code? 
I have the same problem.
thank you!

**Comment by DanielGoldfarb** [comment] 2021-01-02 23:35
@hmhjapan   A number of things have changed since this issue was opened almost 10 months ago.  The main thing to know is that `returnfig=True` now ***does*** return a tuple the first element of which is the Figure, and the second element of which is a List of Axes objects.

There is a recent example of someone [**successfully using tkinter here**](https://github.com/matplotlib/mplfinance/issues/304#issuecomment-751532329).   Please take a look and let us know if you have any more questions.
