### ISSUE TITLE
support for matplotlib.animation?

### ISSUE THREAD

**Issue by BailsonJr** [matplotlib/mplfinance#70] opened 2020-03-27 22:02 UTC
I've been trying to use returnfig=True to replot live data with matplotlib.animation, but the new axes do not update on the original figure. I believe this is due to the fact that a new figure and axes are created in mplfinance.
A config setting for plot, or a new function, to update axes rather than return a new figure and axes would help with this I think.

**Comment by BailsonJr** [comment] 2020-03-27 22:05
I suppose this comment didn't really have a question in it, so...
Is this a feature you'd be interested in implementing?

**Comment by DanielGoldfarb** [comment] 2020-03-27 22:32
`returnfig` has limited value (you can only do a few things with it), because, as you mentioned, the Figure and Axes were created by mplfinance, and the Figure is already "full" with the axes that were created.  **[But it was easy to do and allows support for tkinter](https://github.com/matplotlib/mplfinance/issues/46)** so it definitely has some value.

I don't know what you mean by
> A config setting for plot, or a new function, to update axes rather than return a new figure and axes would help with this I think.

Can you please explain?

There is already **[an issue to support animation here](https://github.com/matplotlib/mplfinance/issues/25)** although several other issues/enhancements are ahead if it, in terms of priority (unless, of course, you or someone else volunteers to do the work?)

And there is **[an enhancement request here to be able to pass your own Figure and Axes into `mpl.plot()`](https://github.com/matplotlib/mplfinance/issues/17)** which I hope begin work on in about week.

**Comment by BailsonJr** [comment] 2020-03-28 04:42
Oh, excellent. These two feature requests are exactly what I was thinking of. Glad to hear that.

**Comment by DanielGoldfarb** [comment] 2020-03-29 01:28
Duplicate of #25 and 
Duplicate of #17

**Closed by DanielGoldfarb** 2020-03-29 01:28 UTC
Labels: question
