### ISSUE TITLE
Bug Report: mac os: fig window won't close (exit)

### ISSUE THREAD

**Issue by mth75** [matplotlib/mplfinance#436] opened 2021-08-23 11:09 UTC
I'm using a mplfinance figure chart as an option in my own developed tradebot. I'm running a bot from a ordinary (Mac OS) terminal and generate a chart when needed by pressing a key (which executes a function and generates a chart).

```
def chart():
    df = dataframe()
    df.index = pd.DatetimeIndex(df['timestamp'])
    df = df.iloc[::-1]
    mpf.plot(df, type='candle', style='charles', title= coin, ylabel = 'Price (€)', volume=True ,warn_too_much_data=9999999)
```

However, the figure window can't be closed. While clicking the red (stop/exit) button the window freezes but the script continues.

So the question would be, how can I gracefully exit the fig window and let the script resume?

Desktop:
Mac OS Big Sur
browser (not using)
latest

**Comment by DanielGoldfarb** [comment] 2021-08-23 12:08
Hi. Before I try to reproduce this, can you show the entire script from where function `chart()` gets called?

Since you have said "and generate a chart when needed by pressing a key (which executes a function and generates a chart)" it seems to me possible that there is some "interactivity" going on in that script that is preventing the matplotlib backend from receiving the gui close event on the plot window (since clearly the script itself has been set up to receive, at the very least, a key-press event).

Thank you.

**Comment by mth75** [comment] 2021-08-23 13:06
> Hi. Before I try to reproduce this, can you show the entire script from where function chart() gets called?


Thanks for your quick enter. The entire script is my tradebot ( I rather not share it at this stage :-) ). The script is normally running in a loop and getting constant ticker price updates until a event triggers a buy or sell action. I hope that this is sufficient information?

**Comment by DanielGoldfarb** [comment] 2021-08-23 16:30
It seems very much likely that this is *not* a bug with mplfinance nor matplotlib, but that you have, in your script, taken over event handling so that the matplotlib backend is not receiving any events.  I will give you some general advice here, that may help, but without seeing your exact event handling code I won't be able to be more specific in my suggestions (you don't have to include your trade decision code, just show kind of where that falls within the overall event handling code).

So here is what I might suggest in a general way.  You will have to research how to catch the mouse click events, and specifically the one that requests closing the plot.

You will probably want access to the mplfinance Figure, which you can get by setting [**`returnfig=True`**](https://github.com/matplotlib/mplfinance/wiki/Acessing-mplfinance-Figure-and-Axes-objects).
```python
    fig, axlist = mpf.plot(df,...,returnfig=True)
```
Once you have done this you will have to call `mpf.show()` to display the plot, and you may (depending on how you handle events) want to not block when calling show: `mpf.show(block=False)`.   When you get the mouse click to close the window then you can close the window by calling `fig.close()` and/or `del fig`.

**Comment by mth75** [comment] 2021-08-23 16:49
Thank you very much for your help. Before I forget, i'm very impressed with your work. I will try and will let you know the results.

**Comment by mth75** [comment] 2021-08-23 23:34
I have stripped backed the script, and the problem seems to be picking up the while loop after "closing" the fig. window. (which remains open on Mac OS with the well known beachball ...).  

`coin = 'BTC' 
bot_status = 'trading'

def limit():
    timeout = 0.5
    print(end='')
    rlist, _, _ = select([sys.stdin], [], [], timeout)
    if rlist:
        s = sys.stdin.readline().strip()
        if s == 'g':
            print('\033[1;34m show chart')
            chart()


def dataframe():
    response = <api exchange>.candles(coin + '-EUR', '1m', {})
    ohlcv = []
    for s in range(len(response)):
        timestamp = (int(response[s][0]))/1000
        open = float(response[s][1])
        high = float(response[s][2])
        low = float(response[s][3])
        close = float(response[s][4])
        volume = float(response[s][5])
        candles = {'timestamp': (datetime.utcfromtimestamp(timestamp).strftime('%Y-%m-%d %H:%M:%S')), 'open': open, 'high': high, 'low': low, 'close': close, 'volume': volume}
        ohlcv.append(candles)
        dataframe = pd.DataFrame(data=ohlcv, dtype=float)
    return dataframe


def chart():
    global bot_status
    df = dataframe()
    df.index = pd.DatetimeIndex(df['timestamp'])
    df = df.iloc[::-1]
    s = mpf.make_mpf_style(base_mpf_style='charles', gridcolor='#555555', gridstyle="--", rc={'axes.edgecolor': 'white', 'font.size': 5})
    fig, axlist = mpf.plot(df, type='candle', style=s, title= coin, ylabel = 'Price (€)', volume=True, warn_too_much_data=9999999, returnfig=True)
    mpf.show(block=True)


# trade loop
while bot_status == 'trading':
    limit()
    print('test')
`

**Comment by DanielGoldfarb** [comment] 2021-08-29 01:33
Thanks.  I just wanted that info.  Good to know.  I hope to have time to look into this after Tuesday.

**Comment by mth75** [comment] 2021-08-31 03:48
Thank you, I hope you find the time to solve this one, I could use the chart function very effective in my tradebot.

**Comment by DanielGoldfarb** [comment] 2021-08-31 17:51
I ran your code on my mac with no problems.  
(macOS High Sierra 10.13.6, although I strongly doubt the OS version has anything to do with this issue).  

To get the code to run, I did the following:
**1.** rewrote `dataframe()` to get data from a file:
```python
    def dataframe():
        dataframe = pd.read_csv('../../data/SP500_NOV2019_Hist.csv',index_col=0, parse_dates=True)
        return dataframe
```
**2.** commented out two lines in `chart()`,
because, with the above change to `dataframe()`, these lines are *no longer needed*:
```python
        #df.index = pd.DatetimeIndex(df['timestamp'])
        #df = df.iloc[::-1]
```

With the above modifications the code runs fine on my machine; see the following video:

https://user-images.githubusercontent.com/11164790/131547524-f3bdaba1-cad9-4069-bc60-2f65842ec8d2.mp4

Notice that after closing the plot, I must click the title bar of the Terminal Window, to bring it into focus, before it will respond to the keyboard again.  (If I do not click to focus the terminal window, but merely begin typing on the keyboard, then I see the mac "spinning color wheel"; which goes away as soon as I click focus on a window).

The fact that it works for me, getting data locally from a file, suggests perhaps that the issue is *not* related to package `select` and polling for IO (as I first suspected), but rather may be related to the exchange api you are using (or to its interaction with `select`).  You may want to test this also on your machine, to see if getting the data locally from a file resolves the issue; if so, it would strongly implicate the exchange api.

---

It is very unclear to me what you are trying to accomplish with this User Interface:  You have some kind of a bot running, perhaps printing something to the screen, and you want the ability to type "`g <enter>`" to plot the data at that point in time.  Are there other commands that you want to be able to enter (besides "g")?  If so, what?   And what kind of information is being output while the UI is awaiting commands?  **If you can describe more precisely what you are ultimately looking to accomplish**, others (including myself) may be able to suggest a better and/or more practical approach.  

You seem to have already decided that this particular way of doing things is the best approach to accomplish your goal, but you have not stated any specifics about your goal(s).  You only provided a general statement of wanting to use mplfinance as a chart within the context of some trading bot.  But you have not indicated, for example, when you might decide to look at the chart, what information you are looking at in order to make that decision, etc.  My point is, as stated above, perhaps there is a better solution to you goals.  If you were not having any problems with your user interface, then I would not say anything.  But the fact that it is not working as you would like, and almost certainly the issue you are seeing has nothing to do with the mplfinance package, together these suggest that there is likely a better approach.

**Comment by mth75** [comment] 2021-08-31 21:04
Hi Daniel, thanks for your analyses. In answer to your questions:

I'm trying to use the chart, just for a quick look (for starters) at trend and volumes, make up my mind about the trend, close the chart (on which point the script would continue) and overrule some parameters manual (or not) all during the running script (bot). 
For instance, I could overrule the precalculated buy or sell price or commit a instant buy or sell order after closing the chart. 

No keyboard input is needed while showing the chart.

This workflow is faster then using the chart from my Broker/Exchange and of course shows only the chosen/dataframe timeperiod. 

I concur that the cause of my problems could be in the dataframe, so I'll dig in deeper.

Attached a video to get a feeling. If I could somehow force the chart (in my script) to close this could help.

https://user-images.githubusercontent.com/46650192/131575424-8d4c1ed0-59e2-4c44-9bf4-e6fd23f2f0a4.mov

**Comment by mth75** [comment] 2021-08-31 21:30
I also noticed that the figure window layout (the icons) is quite different on your Mac OS install. I suspect that matplotlib generates the figure?

**Comment by DanielGoldfarb** [comment] 2021-08-31 22:48
I see you are using PyCharm.  So you are note really running a python script "from a ordinary (Mac OS) terminal."  

I am not familiar with PyCharm, but I have seen reports of things not necessarily behaving normally under PyCharm.  It does some stuff on its own.  

The appearance of the Figure window depends on which matplotlib backend is being used.  Possibly PyCharm is using its own custom backend which may be related to your problem.  

I suggest, near the top of your script, after all the imports, add the following two lines:
```python
import matplotlib
print('backend=',matplotlib.get_backend())
```
On my mac it prints out `backend= Qt5Agg`.   What does yours print out?

**Comment by mth75** [comment] 2021-08-31 23:04
> see you are using PyCharm. So you are note really running a python script "from a ordinary (Mac OS) terminal."

Pycharm for development, the scripts run in normal Mac OS terminals (see my earlier video), the Pycharm you in the window bars is only a folder name.

The result of the backend = MacOSX

**Comment by mth75** [comment] 2021-08-31 23:57
I think I solved it (thanks to the guidance in your questions)!

I installed on my Macs:
pip3 install PyQt5

and added to my script:

import matplotlib
matplotlib.use('Qt5Agg')

works!

Conclusion, not a bug but a dependency?

Thank you Daniel!

**Comment by DanielGoldfarb** [comment] 2021-09-01 01:31
Great news.  Glad to hear.  All the best.

**Closed by DanielGoldfarb** 2021-09-01 01:31 UTC
Labels: question
