### ISSUE TITLE
where is the generated document file build/index.html stored

### ISSUE THREAD

**Issue by mauphung** [matplotlib/mplfinance#445] opened 2021-09-14 14:24 UTC
Run "make html" to generate HTML. Then view build/index.html.
Please tell me where is the generated file build/index.html stored?
I'm running on Windows 10.

**Comment by DanielGoldfarb** [comment] 2021-09-14 15:04
duplicate of #119 

[**Please see my comments here**](https://github.com/matplotlib/mplfinance/issues/119#issuecomment-623435548).  If you would like to help fix the old documentation, you contribution will be greatly appreciated.

In the meantime, [**the new api documentation remains here**](https://github.com/matplotlib/mplfinance#contents-and-tutorials) and at the links therein.

**Closed by DanielGoldfarb** 2021-09-14 15:04 UTC
Labels: question
