### ISSUE TITLE
 err = f'NOT is_color_like() for {key}[\'{updown}\'] = {colors[updown]}'

### ISSUE THREAD

**Issue by thePragmaticOwl** [matplotlib/mplfinance#51] opened 2020-03-12 19:53 UTC
Hi,
Getting this error:
Debian, Python 3.5
    import mplfinance as mpf
  File "/usr/local/lib/python3.5/dist-packages/mplfinance/__init__.py", line 1, in <module>
    from mplfinance.plotting       import plot, make_addplot
  File "/usr/local/lib/python3.5/dist-packages/mplfinance/plotting.py", line 15, in <module>
    from mplfinance._utils import _construct_ohlc_collections
  File "/usr/local/lib/python3.5/dist-packages/mplfinance/_utils.py", line 15, in <module>
    from mplfinance._styles import _get_mpfstyle
  File "/usr/local/lib/python3.5/dist-packages/mplfinance/_styles.py", line 215
    err = f'NOT is_color_like() for {key}[\'{updown}\'] = {colors[updown]}'
------------------
    mc = mpf.make_marketcolors(ohlc='black')
    s  = mpf.make_mpf_style(marketcolors=mc)                                    
    mpf.plot(item['Close'],type='bars',style=s)
-------------------
This code works perfectly within the Anaconda Env. 
I cannot run in on my VPS...

Thanks in advance...

**Comment by DanielGoldfarb** [comment] 2020-03-12 20:20
What is VPS ?  (I also have Anaconda environment, so I am concerned I won't be able to reproduce).

[The code there](https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/_styles.py#L203-L217) is calling `matplotlib.colors.is_color_like()` which appears to be returning `False` in your case.   It *may* be that there is something different about your matplotlib install in your VPS environment. 

The f'string (`err = f'NOT is_color_like() for {key}['{updown}'] = {colors[updown]}'`) in the exception is attempting to print the value that was passed into `matplotlib.colors.is_color_like()` so as to see possibly why it is returning `False`.  **Are you ***not*** seeing the output from the f'string?**   
**If you do see it, can you post it here please?  (Please post *all* of the output from the exception).**

On a separate note (which *may or may not* be related) your code here: `mpf.plot(item['Close'],type='bars',style=s)` appears to be passing a single column (instead of a dataframe) as the data passed to `mpf.plot()`.  **Is that what it is doing?**

This may be easier to answer/debug if I could see all the code (not just three lines; which on the surface of things look fine as far as colors go).  **Can you place the code in a gist or repository for me to see?**  Thanks. --Daniel

**Comment by thePragmaticOwl** [comment] 2020-03-14 15:40
Hi Daniel,

VPS, virtual private server. This is my 'production' environment (Debian 9.11, Python 2.7 & Python 3.5)
---------------------------- same output for both Python versions
"Are you not seeing the output from the f'string?"
root@pgsowa1:/home/pgsowa/python_pg# python ai_feed_HK.py
Traceback (most recent call last):
  File "ai_feed_HK.py", line 13, in <module>
    import mplfinance as mpf
  File "/usr/local/lib/python2.7/dist-packages/mplfinance/__init__.py", line 1, in <module>
    from mplfinance.plotting       import plot, make_addplot
  File "/usr/local/lib/python2.7/dist-packages/mplfinance/plotting.py", line 14, in <module>
    from mplfinance._utils import _construct_ohlc_collections
  File "/usr/local/lib/python2.7/dist-packages/mplfinance/_utils.py", line 15, in <module>
    from mplfinance._styles import _get_mpfstyle
  File "/usr/local/lib/python2.7/dist-packages/mplfinance/_styles.py", line 215
    err = f'NOT is_color_like() for {key}[\'{updown}\'] = {colors[updown]}'
                                                                          ^
SyntaxError: invalid syntax
--------------------------
mpf.plot(item['Close'],type='bars',style=s) appears to be passing a single column (instead of a dataframe) as the data passed to mpf.plot(). Is that what it is doing?

Same output for dataframe: mpf.plot(item,type='bars',style=s)
---------------------------
Can you place the code in a gist or repository for me to see?

in progress

------------------
It may be that there is something different about your matplotlib install in your VPS environment.

It does make sense, matplotlib versions differs. My Windows Anaconda env has matplotlib 3.1.1, vps 3.0.3. I am considering that, it also might be some package dependencies issue. 

Still trying to figure out what's wrong...
Once sorted I will let you know...

Thanks
Michal

**Comment by DanielGoldfarb** [comment] 2020-03-15 01:07
Thank you.  THis is helpful.

> err = f'NOT is_color_like() for {key}['{updown}'] = {colors[updown]}'
> ^
> SyntaxError: invalid syntax

Ugh!   This looks like I have a syntax error in the line of code that is supposed to report what value is **`not is_color_like()`    I thought I had tested that.  Guess not.  Will continue looking into this.  Thanks again.

**Comment by gokulc** [comment] 2020-03-15 05:21
I get it right on -- import mplfinance. Is there any temporary fix to get around for the time?

**Comment by DanielGoldfarb** [comment] 2020-03-15 05:44
> I get it right on -- import mplfinance. Is there any temporary fix to get around for the time?

So far, I am undable to reproduce the problem; so until I can, I cannot suggest a quick fix.

I would suggest howeverthat you make sure you are running Python 3.6 or higher.  **`mplfinance` is not supported for versions of python earlier than 3.6**

You may also want to upgrade to the most recent version of **`matplotlib`**

**Comment by DanielGoldfarb** [comment] 2020-03-15 05:53
Actually, I just noticed that appears to be the issue @thePragmaticOwl in your original post **it appears you are using Python 3.5, whereas the line of code that is failing with a sytax error:**

    err = f'NOT is_color_like() for {key}['{updown}'] = {colors[updown]}'

**is using an f'string.   f'strings were introduced in Python 3.6**

I'm now feeling 90% certain that's the problem.  That would also explain failing right on import.  If so, then a quick fix would be to change that line of code to one of the older types of Python string formatting.

I'm going to look into whether there is something I can import from __future__ to make the f'strings compatable with older versions of Python.  ***Officially*** **`mplfinance` is supported only for Python 3.6 and higher,** but if there are simple/small things I can do to make it compatible with older version I will do it.  None-the-less, I still recommend upgrading your Python version.

**Comment by gokulc** [comment] 2020-03-15 08:21
OK, Installing version 3.6 worked for me. Thanks.

**Comment by DanielGoldfarb** [comment] 2020-03-15 12:15
**@gokulc Thanks!**   
I think that confirms the issue is that you must have **Python 3.6 or greater.**   For the record, at this point in time [**matplotlib** also requires Python 3.6 or greater](https://matplotlib.org/users/installing.html#dependencies).   Closing this issue.

**Closed by DanielGoldfarb** 2020-03-15 12:15 UTC
Labels: question
