### ISSUE TITLE
Feature Request: Additional optional lower (or upper) panels

### ISSUE THREAD

**Issue by hrpomrx** [matplotlib/mplfinance#92] opened 2020-04-13 21:28 UTC
This is a great package, thank you for the hard work! 

Having to add indicators to the volume (lower) panel means it gets quite cluttered when multiple indicators like ADX/RSI/OBV, etc., are added.

A nice solution would be to be able to add a lower panel (or multiple lower panels), or possibly a panel above the price (much in the same way as stockcharts.com). Perhaps such a feature exists already, or is able to be implemented and I missed the documentation?

**Comment by DanielGoldfarb** [comment] 2020-04-13 23:04
You can see there is **[some discussion of multiple panels in this issue](https://github.com/matplotlib/mplfinance/issues/17)** particularly **[in this comment](https://github.com/matplotlib/mplfinance/issues/17#issuecomment-581095725)**.

However _presently_ that is not part of the medium term plan anymore (although it may be in the future) **[as noted in the bottom half of this comment](https://github.com/matplotlib/mplfinance/issues/17#issuecomment-607382801)** ...  

For now the plan is to add the ability for users to use matplotlib to create their own subplots and pass them in.  That seems to be a very popular request (which solves your request as well).   

That said, personally for my own needs, I would prefer something simpler, that does not require outside matplotlib work, **[as with my original proposal of multiple panels](https://github.com/matplotlib/mplfinance/issues/17#issuecomment-581095725)** (as you are suggesting) with perhaps two or three smaller panels for indicators in addition to the main panel and with the ability to decided how many of the smaller panels are below and how many above.

Duplicate of #17

**Closed by DanielGoldfarb** 2020-04-13 23:04 UTC
Labels: enhancement

**Comment by hrpomrx** [comment] 2020-04-14 02:19
OK thanks, I somehow missed #17 ; I like the ideas proposed in that one.
