### ISSUE TITLE
Feature Request: fill_between function with multiple regions and different colors

### ISSUE THREAD

**Issue by qililiu** [matplotlib/mplfinance#292] opened 2020-11-12 03:40 UTC
**Is your feature request related to a problem? Please describe.**
I am trying to show the LONG and SHORT regions of stocks based on the MA20, MA60, MA120. I am always frustrated by the fill_between function. It can only fill one region with a single color. What I want to do is: 1) to show the region in green where  MA20>MA60>MA120, 2) to show the region in gray where MA20>MA60>MA120, 3) the red and gray regions are showed simultaneously.

**Describe the solution you'd like**
In the fill_between function, we can have multiple fill_between call.
fill_between=dict(y1=y1value,y2=y2value,where=where_value1,alpha=0.5,color='r')
fill_between=dict(y1=y3value,y4=y2value,where=where_value2,alpha=0.5,color='g')

**Describe alternatives you've considered**
fill_between=dict(y1=[y11value,y12value],y2=[y21value,y22value],where=[where_value1,where_value2],alpha=[0.5,0.5],color=['r','g'])

**Additional context**

**Comment by DanielGoldfarb** [comment] 2020-11-13 18:22
We will definitely do this!   

Not sure when.  Most likely within the next 2 to 3 months.

duplicate of #218

**Closed by DanielGoldfarb** 2020-11-13 18:22 UTC
Labels: enhancement
