### ISSUE TITLE
No module named mplfinance in conda environment

### ISSUE THREAD

**Issue by damodar-basyal** [matplotlib/mplfinance#99] opened 2020-04-18 16:39 UTC
I am trying to create ohlc graph. I have install mplfinance version 0.12.3a3 in conda environment using pip install. However, while running code in jupyter notebook, it says no module named mplfinance. How can i solve this issue?

**Comment by DanielGoldfarb** [comment] 2020-04-19 01:57
resolved via email

**Closed by DanielGoldfarb** 2020-04-19 01:57 UTC
Labels: question

**Comment by MMSYYZ** [comment] 2020-04-20 08:25
Same here. How did you solve the issue?

**Comment by DanielGoldfarb** [comment] 2020-04-20 08:56
This is what I had sent to Damodar:

 I am guessing that pip may have installed it in a place that your python sys.path does not include.

    In general, with conda, you must first activate the conda environment into which you want to install mplfinance, *and you must use the pip that is installed by conda in that environment.*   There are other ways that work but that is the usual one.

   At this point you can try again as described above, or to figure out what went wrong you may want to examine sys.path from the jupyter notbook (compare with command line python just to confirm they are the same), and try to find where in the file system mplfinance got installed.  More information on sys.path here:  https://bic-berkeley.github.io/psych-214-fall-2016/sys_path.html

Let me know if that helps.  

---

But apparently Damodar had found some issue with the jupyter setup ... that it was running under base or root instead of under the environment that was intended (something like that).

**Comment by MMSYYZ** [comment] 2020-04-21 04:18
Hi Daniel,

I first pip install mplfinance with Windows Command Prompt and tried importing it in Jupyter Notebook and apparently it did not work.
Then I just tried pip install again in Anaconda Prompt and somehow it worked.

Hope the info helps!

________________________________

**Comment by DanielGoldfarb** [comment] 2020-04-21 05:09
Thanks.  Good luck.
