### ISSUE TITLE
make_addplot with a legend

### ISSUE THREAD

**Issue by prRZ5F4LXZ** [matplotlib/mplfinance#409] opened 2021-06-16 03:48 UTC
```
import yfinance as yf
df = yf.Ticker('MSFT').history(period='1y')
import mplfinance as mpf
import pandas_ta as ta
apdict = mpf.make_addplot(ta.sma(df['Close'], length=10), linestyle='dotted')
mpf.plot(df, block=False, volume=True, addplot=apdict, savefig='/tmp/MSFT.pdf')
```

I can plot some data using `make_addplot()`. But I don't see an option that can add a legend.

https://github.com/matplotlib/mplfinance/blob/master/src/mplfinance/plotting.py#L1024

Is there a way to do so? Thanks.

**Comment by DanielGoldfarb** [comment] 2021-07-14 19:12
duplicate of #276

**Closed by DanielGoldfarb** 2021-07-14 19:12 UTC
Labels: question
