### ISSUE TITLE
Bug Report:  y axis value on renko figure

### ISSUE THREAD

**Issue by zoli2750** [matplotlib/mplfinance#145] opened 2020-05-29 19:06 UTC
I really like the new renko type, just one relatively minor issue:
hovering with the mouse over the chart the y value on the right lower corner writes a number between 0 and 1(float), not the corresponding price value.

**Comment by DanielGoldfarb** [comment] 2020-06-02 02:03
My hover numbers look fine.  I just now re-ran and tested [every renko example in in the examples folder](https://github.com/matplotlib/mplfinance/blob/master/examples/price-movement_plots.ipynb).  All the hover numbers all look fine to me.

Please provide your **data, and code**, so that I can reproduce and see the problem.

**Comment by zoli2750** [comment] 2020-06-02 06:45
Thank you very much for your effort investigating my findings, I appreciate it much.
I've reopened my files, all of the mpl_finance codes behaving the same, displaying the y axis value between zero and 1, candle and renko types as well.
I have opened many of the matplotlib example files, all of them displaying correctly the y axis value.

I'm aware that this issue might be strange, I'm not against to close it and deal with it when other users reporting similar. 

python x64, matplotlib, mpl_finance versions are the latest, (3.8.3, 3.2.1, 0.12.4a0)
system: win10

_Here is a sample code of an mpl_finance I used:_
import pandas as pd
import mplfinance as mpf

foldername = 'C://api/ibinsync/Testfiles/hystorical_data/data/'
filename = foldername + 'SP500_NOV2019_IDay.csv'

intraday = pd.read_csv(filename,index_col=0,parse_dates=True)
intraday = intraday.drop('Volume',axis=1) # Volume is zero anyway for this intraday data set
intraday.index.name = 'Date'
intraday.shape
intraday.head(3)
intraday.tail(3)

iday = intraday.loc['2019-11-06 15:00':'2019-11-06 16:00',:]
mpf.plot(iday,type='renko',renko_params=dict(brick_size=0.1))

Screenshot:
![mpl_finance](https://user-images.githubusercontent.com/46138139/83487381-3b54d680-a4ab-11ea-8ffa-07d46d8bf23a.JPG)


_Here is a matplotlib code  from the matplotlib site, I'have picked a short one:_
_simple_legend02.py_

import matplotlib.pyplot as plt
fig, ax = plt.subplots()
line1, = ax.plot([1, 2, 3], label="Line 1", linestyle='--')
line2, = ax.plot([3, 2, 1], label="Line 2", linewidth=4)
first_legend = ax.legend(handles=[line1], loc='upper right')
ax.add_artist(first_legend)
ax.legend(handles=[line2], loc='lower right')
plt.show()

Screenshot:
![simple_legend02](https://user-images.githubusercontent.com/46138139/83487433-50316a00-a4ab-11ea-987a-bf6e308c02d3.JPG)

**Comment by DanielGoldfarb** [comment] 2020-06-03 01:45
Thank you.  I was able to reproduce using mplfinance v0.12.4a0 and the issue is not limited to renko plots but appears to affect all plots.

I was not yet able to determine what is causing it, but I do know that the new version (currently in my fork) that I expect to be released sometime next week does _not_ have the problem.  So you can expect it to be fixed in approximately one week.

**Comment by zoli2750** [comment] 2020-06-03 13:41
Thank You

**Comment by DanielGoldfarb** [comment] 2020-06-07 23:48
new version 0.12.5 just released to [Pypi](https://pypi.org/project/mplfinance/) fixes this

**Closed by DanielGoldfarb** 2020-06-07 23:48 UTC
Labels: bug, in progress

**Comment by farzinaa** [comment] 2022-02-01 23:33
Hi. 
This issue is also present in the latest version, namely 0.12.8b6. 
Thanks
