### ISSUE TITLE
Bug Report: No close plot for savefig, error 20 open plot's

### ISSUE THREAD

**Issue by Replog** [matplotlib/mplfinance#131] opened 2020-05-11 14:15 UTC
mpf.plot(df, type='candle', mav=(100, ), style='charles', title="EURUSD", savefig='save.png')

after> 20 times leads to an error that 20 charts are open

mplfinance\plotting.py:226: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig = plt.figure()

**Comment by DanielGoldfarb** [comment] 2020-05-11 14:52
This is not a bug, but is a **matplotlib** feature intended to prevent leaking memory.  

We have the same issue when running mplfinance regression tests.  **[The solution is to use the `returnfig` kwarg and close the figure as done here](https://github.com/matplotlib/mplfinance/blob/master/tests/test_addplot.py#L34-L37)**.

In the future, we will consider adding kwarg `closefig=True`

**Comment by DanielGoldfarb** [comment] 2020-05-11 14:56
Perhaps when user sets `savefig` and does ***not*** set `returnfig`, then we should close the Figure by default?  Or should we prefer the user to be explicit with `closefig=True`?   Thoughts?

**Comment by Replog** [comment] 2020-05-11 15:48
I think it's worth closing by default

**Comment by DanielGoldfarb** [comment] 2020-05-11 15:48
For the next release, I have added a `closefig` kwarg.
**The default value will be 'auto'**, which means `mpf.plot()` will attempt to determine when it is "safe" to close the figure.  This default behavior can be overridden by passing `closefig=True` or `closefig=False`.

At this time, it is **unsafe** or inappropriate to close the Figure **if**
- `returnfig=True` **or**
- `block=False` **or**
- user has passed in their own Figure and Axes

Otherwise it is considered safe to close the Figure.  With this enhancement, most users who want to create more than Figures via `mpf.plot()` will ***not*** have to `import pyplot` and close the Figure themselves.

**Comment by richinvest** [comment] 2020-05-24 15:00
I am wondering how I can close the Figure by myself as an intermediate solution?

**Comment by DanielGoldfarb** [comment] 2020-05-24 16:01
I expect to merge in this enhancement (closing the figure) sometime tomorrow (just finishing up the documentation now).

In the meantime, the short term solution is to have `mpf.plot()` return the figure and close it:

    import matplotlib.pyplot as plt
    ...
    fig, ax = mpf.plot(data, ... ,returnfig=True)
    plt.close(fig)

**Comment by fxhuhn** [comment] 2020-05-27 05:21
Grreat, in the meantime i use `plt.close(all)`

**Comment by DanielGoldfarb** [comment] 2020-06-07 23:46
new version 0.12.5 just released to [Pypi](https://pypi.org/project/mplfinance/) automatically closes plots when "appropriate" and contains kwarg ` closefig ` which can be set to `"auto"` (default), `True`, or `False`.

**Closed by DanielGoldfarb** 2020-06-07 23:46 UTC
Labels: enhancement, in progress
